[book]
# CI appends the crate version.
title = "emacs-module-rs"
authors = ["ubolonton"]
src = "src"

[output.html]
additional-css = ["custom.css"]
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/ubolonton/emacs-module-rs"
edit-url-template = "https://github.com/ubolonton/emacs-module-rs/edit/master/docs/guide/{path}"

# The examples need the `emacs` crate, which the Rust Playground does not have.
[output.html.playground]
runnable = false
