name: CI

on:
  push:
    branches:
      - master
      - ci
      - github-actions
    paths-ignore:
      - guide/**
  pull_request:
    branches:
      - master
    paths-ignore:
      - guide/**

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-12
          - macos-13
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-2019
          - windows-2022
        emacs-version:
          - '27.2'
          - '28.2'
          - '29.2'
        include:
          - os: macos-12
            emacs-version: '26.3'
          - os: ubuntu-20.04
            emacs-version: '26.3'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Rust
        run: |
          rustup install stable
          rustc -Vv
          cargo -V

      - uses: actions/checkout@v4

      - name: Build
        run: ./bin/build

      - run: cargo test --all

      - uses: purcell/setup-emacs@v6.0
        if: runner.os != 'Windows'
        with:
          version: ${{ matrix.emacs-version }}

      - uses: jcs090218/setup-emacs-windows@master
        if: runner.os == 'Windows'
        with:
          version: ${{ matrix.emacs-version }}

      - run: ./bin/test

  ci-aarch64:
    runs-on: macos-12
    steps:
      - name: Set up Rust
        run: |
          rustup install stable
          rustup target add aarch64-apple-darwin
          rustc -Vv
          cargo -V

      - uses: actions/checkout@v4

      - name: Build
        run: ./bin/build
        env:
          CARGO_BUILD_TARGET: aarch64-apple-darwin
