name: CI

on:
  push:
    branches:
      - master
      - ci
      - github-actions
    paths-ignore:
      - guide/**
  pull_request:
    branches:
      - master
    paths-ignore:
      - guide/**

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15
          - macos-26
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-22.04-arm
          - ubuntu-24.04-arm
          - windows-2022
          - windows-2025
        emacs-version:
          - '28.2'
          - '29.4'
          - '30.1'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Rust
        run: |
          rustup install stable
          rustc -Vv
          cargo -V

      - uses: actions/checkout@v6
        with:
          # XXX: Partial protection. We can't currently do better. Maybe move the 3rd-party actions
          # up? See https://github.com/actions/checkout/issues/485.
          persist-credentials: false

      - name: Build
        run: ./bin/build

      - run: cargo test --all

      - uses: purcell/setup-emacs@master
        if: runner.os != 'Windows'
        with:
          version: ${{ matrix.emacs-version }}

      - uses: jcs090218/setup-emacs-windows@master
        if: runner.os == 'Windows'
        with:
          version: ${{ matrix.emacs-version }}

      - run: ./bin/test
